import React, { useState } from 'react';
import { Download, Copy, Heart, Search, Filter } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

const testSvgUrl1 = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" stroke="#0ea5e9" stroke-width="4" fill="none"/></svg>`;
const testSvgUrl2 = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="20" y="20" width="60" height="60" stroke="#f43f5e" stroke-width="4" fill="none"/></svg>`;
const testSvgUrl3 = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><polygon points="50 15, 100 100, 0 100" stroke="#a855f7" stroke-width="4" fill="none"/></svg>`;
const testSvgUrl4 = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none" stroke="#22d3ee" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>`;

const mockGalleryData = [
  { id: 1, svg: testSvgUrl1, prompt: "A glowing blue sci-fi ring", author: "Alex D.", likes: 124 },
  { id: 2, svg: testSvgUrl2, prompt: "Minimalist neon square", author: "Sarah W.", likes: 89 },
  { id: 3, svg: testSvgUrl3, prompt: "Purple gradient triangle", author: "Jordan K.", likes: 256 },
  { id: 4, svg: testSvgUrl4, prompt: "Cyan pulse wave line", author: "Emily C.", likes: 45 },
  { id: 5, svg: testSvgUrl4, prompt: "Cyberpunk heart monitor graph", author: "Chris M.", likes: 312 },
  { id: 6, svg: testSvgUrl1, prompt: "Minimalist target interface", author: "Taylor P.", likes: 78 }
];

export default function Gallery() {
  const [search, setSearch] = useState('');
  
  const filtered = mockGalleryData.filter(item => 
    item.prompt.toLowerCase().includes(search.toLowerCase()) ||
    item.author.toLowerCase().includes(search.toLowerCase())
  );

  const downloadGallerySvg = (svgCode, id) => {
    if (!svgCode) return;
    const blob = new Blob([svgCode], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `svg-gallery-${id}.svg`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    }, 200);
  };

  const copyGallerySvg = (svgCode) => {
    if (!svgCode) return;
    navigator.clipboard.writeText(svgCode);
    alert('SVG code copied to clipboard!');
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 pt-24 text-slate-100 min-h-screen">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
          <h1 className="text-4xl font-black mb-2 tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500">
            Community Discovery
          </h1>
          <p className="text-slate-400">Explore and remix vector art generated by the community.</p>
        </motion.div>
        
        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="flex items-center gap-3">
          <div className="relative glass-card rounded-xl border border-slate-700 overflow-hidden w-full md:w-80 transition-all focus-within:border-cyan-500/50 focus-within:ring-1 focus-within:ring-cyan-500/50">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
            <input 
              type="text" 
              placeholder="Search prompts or artists..." 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-transparent outline-none pl-10 pr-4 py-3 text-sm placeholder-slate-500"
            />
          </div>
          <button className="glass-card p-3 rounded-xl border border-slate-700 hover:bg-slate-800 transition-colors">
            <Filter className="w-5 h-5 text-slate-400" />
          </button>
        </motion.div>
      </div>

      {/* Grid */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6"
      >
        <AnimatePresence>
          {filtered.map((item, i) => (
            <motion.div
              key={item.id}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.3, delay: i * 0.05 }}
              whileHover={{ y: -5 }}
              className="glass-card rounded-2xl border border-slate-700 overflow-hidden group flex flex-col"
            >
              {/* Media Container */}
              <div className="relative aspect-square flex items-center justify-center p-8 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCI+PHBhdGggZD0iTTIwIDBoLTIwdjIwaDIwdi0yMHptLTE5IDF2MThoMThWMWgtMTh6IiBmaWxsPSIjMWUyOTNiIiBmaWxsLW9wYWNpdHk9IjAuNSIvPjwvc3ZnPg==')]">
                <div 
                  className="w-full h-full transform transition-transform duration-500 group-hover:scale-110 drop-shadow-[0_0_15px_rgba(255,255,255,0.1)] flex items-center justify-center"
                  dangerouslySetInnerHTML={{ __html: item.svg }} 
                />
                
                {/* Overlay actions */}
                <div className="absolute inset-0 bg-slate-900/60 opacity-0 group-hover:opacity-100 backdrop-blur-sm transition-opacity duration-300 flex items-center justify-center gap-3">
                  <button onClick={() => downloadGallerySvg(item.svg, item.id)} className="w-10 h-10 rounded-full bg-white text-slate-900 flex items-center justify-center hover:bg-cyan-400 hover:text-white transition-all transform hover:scale-110 shadow-lg" title="Download SVG">
                    <Download className="w-4 h-4" />
                  </button>
                  <button onClick={() => copyGallerySvg(item.svg)} className="w-10 h-10 rounded-full bg-slate-800 border border-slate-600 text-slate-300 flex items-center justify-center hover:bg-slate-700 transition-all transform hover:scale-110 shadow-lg" title="Copy XML">
                    <Copy className="w-4 h-4" />
                  </button>
                </div>
              </div>
              
              {/* Info Container */}
              <div className="p-5 border-t border-slate-700/50 bg-slate-900/50 flex flex-col flex-1 justify-between gap-4">
                <div>
                  <h3 className="text-sm font-semibold text-slate-200 line-clamp-2 leading-tight mb-1">"{item.prompt}"</h3>
                  <p className="text-xs text-slate-500">by <span className="text-cyan-400 hover:underline cursor-pointer">{item.author}</span></p>
                </div>
                
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono font-medium tracking-widest text-slate-600 bg-slate-800/50 px-2 py-1 rounded-md">SVG/XML</span>
                  <button className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-pink-500 transition-colors group/like">
                    <Heart className="w-4 h-4 group-hover/like:fill-pink-500" />
                    <span className="font-semibold">{item.likes}</span>
                  </button>
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
      </motion.div>

      {filtered.length === 0 && (
        <div className="text-center py-32 opacity-50">
          <Search className="w-12 h-12 mx-auto text-slate-500 mb-4" />
          <h2 className="text-xl text-slate-300">No generated SVGs found.</h2>
          <p className="text-slate-500">Try adjusting your search terms.</p>
        </div>
      )}
    </div>
  );
}
